In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import f1_score, precision_score,accuracy_score
from sklearn import model_selection
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import ShuffleSplit


In [ ]:
from google.colab import drive
drive.mount('/content/drive')
train = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/covid data/data/finalprob.csv')

#val = pd.read_csv('data/postproc_val.csv')
test = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/covid data/data/finalprobtest.csv')


Mounted at /content/drive


In [ ]:
pd.options.display.max_rows=None
train

class0_pred  class1_pred  username_real  ...  domain_real  domain_fake  label
0        0.554285     0.445715       0.000000  ...     0.000000     0.000000      0
1        0.953478     0.046522       0.000000  ...     0.838903     0.161097      0
2        0.124017     0.875983       0.000000  ...     0.000000     1.000000      1
3        0.950679     0.049321       0.995146  ...     0.838903     0.161097      0
4        0.941731     0.058269       0.000000  ...     0.838903     0.161097      0
5        0.905005     0.094995       0.000000  ...     1.000000     0.000000      0
6        0.933001     0.066999       0.000000  ...     0.994819     0.005181      0
7        0.044262     0.955738       0.000000  ...     0.000000     1.000000      1
8        0.304175     0.695825       0.000000  ...     0.000000     0.000000      1
9        0.299199     0.700801       0.000000  ...     0.500000     0.500000      1
10       0.910189     0.089811       0.000000  ...     0.994819     0.005181      0
11       0.191557     0.808443       0.000000  ...     0.000000     1.000000      1
12       0.325480     0.674520       0.000000  ...     1.000000     0.000000      0
13       0.972537     0.027463       0.000000  ...     0.000000     0.000000      0
14       0.932045     0.067955       0.000000  ...     0.994819     0.005181      0
15       0.932284     0.067716       0.000000  ...     0.838903     0.161097      0
16       0.166429     0.833571       0.000000  ...     0.000000     0.000000      1
17       0.986701     0.013299       0.957451  ...     0.000000     0.000000      0
18       0.242140     0.757860       0.000000  ...     1.000000     0.000000      0
19       0.262613     0.737387       0.000000  ...     0.000000     0.000000      1
20       0.089865     0.910135       0.000000  ...     0.000000     1.000000      1
21       0.627208     0.372792       0.000000  ...     0.000000     0.000000      0
22       0.122305     0.877695       0.000000  ...     0.000000     0.000000      1
23       0.886509     0.113491       1.000000  ...     0.000000     0.000000      0
24       0.291792     0.708208       0.000000  ...     1.000000     0.000000      0
25       0.383984     0.616016       0.000000  ...     0.000000     1.000000      1
26       0.322942     0.677058       0.000000  ...     0.000000     0.000000      1
27       0.876530     0.123470       0.000000  ...     0.000000     0.000000      0
28       0.990205     0.009795       0.000000  ...     0.000000     0.000000      0
29       0.208456     0.791544       0.000000  ...     1.000000     0.000000      0
30       0.108704     0.891296       0.000000  ...     0.000000     1.000000      1
31       0.034709     0.965291       0.000000  ...     0.000000     0.000000      1
32       0.936952     0.063048       0.000000  ...     0.994819     0.005181      0
33       0.403121     0.596879       0.000000  ...     0.000000     0.000000      1
34       0.120672     0.879328       0.000000  ...     0.000000     1.000000      1
35       0.061419     0.938581       0.000000  ...     0.000000     0.000000      1
36       0.886277     0.113723       0.000000  ...     0.838903     0.161097      0
37       0.016737     0.983263       0.000000  ...     0.000000     0.000000      1
38       0.955117     0.044883       0.000000  ...     0.838903     0.161097      0
39       0.031293     0.968707       0.000000  ...     0.000000     0.000000      1
40       0.898888     0.101112       1.000000  ...     1.000000     0.000000      0
41       0.164410     0.835590       0.000000  ...     0.000000     0.000000      1
42       0.955202     0.044798       0.000000  ...     0.000000     0.000000      0
43       0.806485     0.193515       0.000000  ...     1.000000     0.000000      0
44       0.973308     0.026692       0.000000  ...     0.838903     0.161097      0
45       0.957378     0.042622       0.000000  ...     0.838903     0.161097      0
46       0.653363     0.346637       0.000000  ...     0.8

In [ ]:
train.head()

class0_pred  class1_pred  username_real  ...  domain_real  domain_fake  label
0     0.554285     0.445715       0.000000  ...     0.000000     0.000000      0
1     0.953478     0.046522       0.000000  ...     0.838903     0.161097      0
2     0.124017     0.875983       0.000000  ...     0.000000     1.000000      1
3     0.950679     0.049321       0.995146  ...     0.838903     0.161097      0
4     0.941731     0.058269       0.000000  ...     0.838903     0.161097      0

[5 rows x 7 columns]

In [ ]:
train.fillna(0,inplace=True)
test.fillna(0,inplace=True)
train_X = train.iloc[:, :-1].values
train_y = train.iloc[:, -1].values
#val_X = val.iloc[:, :-1].values
#val_y = val.iloc[:, -1].values
test_X = test.iloc[:, :-1].values
test_y = test.iloc[:, -1].values
print(train_X)
print(test_X)

[[0.5542853  0.4457147  0.         0.         0.         0.        ]
 [0.95347817 0.04652183 0.         0.         0.83890317 0.16109683]
 [0.12401743 0.87598257 0.         0.         0.         1.        ]
 ...
 [0.12059059 0.87940941 0.         0.         0.         0.        ]
 [0.35001583 0.64998417 0.         0.         0.         0.        ]
 [0.98004301 0.01995699 0.         0.         0.         0.        ]]
[[0.98719263 0.01280737 0.         0.         0.83890317 0.16109683]
 [0.09811514 0.90188486 0.         0.         0.         0.        ]
 [0.00143316 0.99856684 0.         0.         0.         1.        ]
 ...
 [0.91095475 0.08904525 0.         0.         0.83890317 0.16109683]
 [0.88861524 0.11138476 1.         0.         0.         0.        ]
 [0.53509781 0.46490219 0.         0.         1.         0.        ]]


In [ ]:
cv = ShuffleSplit(n_splits=10, test_size=0.3, random_state=0)

model = LogisticRegression(solver='liblinear', max_iter=400, penalty='l2', random_state=0)
# scores = cross_val_score(model, train_X, train_y, cv=cv, scoring='f1_micro')
# scores.mean()

#train_y.fillna(0,inplace=True)


In [ ]:
model.fit(train_X, train_y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=400,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
# val_scores = cross_val_score(model, val_X, val_y, cv=cv, scoring='f1_micro')
# val_scores.mean()

In [ ]:
#val_predictions = model.predict(val_X)

In [ ]:
#f1_score(val_y, val_predictions, average='micro')

0.9845794392523365

In [ ]:
# test_scores = cross_val_score(model, test_X, test_y, cv=cv, scoring='f1_micro')
# test_scores.mean()

In [ ]:
test_predictions = model.predict(test_X)

In [ ]:
f1_score(test_y, test_predictions, average='micro')

0.9299065420560748

In [ ]:
 precision_score(train_y, test_predictions)

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1305: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if pos_label not in present_labels:


ValueError: ignored

In [ ]:
accuracy_score(test_y,test_predictions)

0.5141744548286604